# netlify.toml

[build]
  publish = "frontend"             # 1. Location of the static HTML files
  functions = "netlify/functions"  # 2. Location of the Node.js function files

# 3. Security and Routing Rules (Solves the connection problem)
[[redirects]]
  from = "/api/analyze"
  to = "/.netlify/functions/analyze"  # Forwards request to the deployed function
  status = 200
  force = true

[[redirects]]
  from = "/api/suggest"
  to = "/.netlify/functions/suggest"
  status = 200
  force = true